# Este arquivo define as regras de anonimização para os campos escolhidos para anonimizar no banco de dados.
# Você pode especificar quais tabelas e quais colunas você deseja anonimizar, e para cada coluna, qual o método de anonimização melhor se encaixa.

# Template: (descomente para usar)

nome_tabela1:
  nome_coluna1: mask_name
  nome_coluna2: mask_email
# Funções de anonimização disponíveis:

# - mask_name: Masks names by replacing them with a generic name.
# - mask_email: Masks emails by replacing them with a generic email.
# - mask_cpf: Masks CPF numbers by replacing them with a generic CPF.
# - mask_phone: Masks phone numbers by replacing them with a generic phone number.

#  Funções genéricas de anonimização:

# - mask_string: Masks strings by replacing them with a generic string.
# - mask_integer: Masks integers by replacing them with a random integer.
# - mask_float: Masks floats by replacing them with a random float.
# - mask_date: Masks dates by replacing them with a random date within a range.
# - mask_boolean: Masks booleans by replacing them with a random boolean.
# - nullify: Nullifies the field value.
# - hash_value: Hashes the field value using SHA-256.
# - id: Generates a unique ID for the field.
