# This file defines the anonymization rules for various fields in the database.

# Template:

# table_name:
#   field1_name: mask_function
#   field2_name: mask_function

# Current available anonymization functions:

# - mask_name: Masks names by replacing them with a generic name.
# - mask_email: Masks emails by replacing them with a generic email.
# - mask_cpf: Masks CPF numbers by replacing them with a generic CPF.
# - mask_phone: Masks phone numbers by replacing them with a generic phone number.

#  Generic functions:

# - mask_string: Masks strings by replacing them with a generic string.
# - mask_integer: Masks integers by replacing them with a random integer.
# - mask_float: Masks floats by replacing them with a random float.
# - mask_date: Masks dates by replacing them with a random date within a range.
# - mask_boolean: Masks booleans by replacing them with a random boolean.
# - nullify: Nullifies the field value.
# - hash_value: Hashes the field value using SHA-256.

clients:
  name: mask_name
  email: mask_email
  cpf: mask_cpf
  phone: mask_phone

test_masking:
  test_string: mask_string
  test_integer: mask_integer
  test_float: mask_float
  test_date: mask_date
  test_boolean: mask_boolean
  test_hashme: hash_value
  test_nullme: nullify
